# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'calculator_pretty.ui'
#
# Created by: PyQt5 UI code generator 5.15.9
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_Dialog(object):
    def setupUi(self, Dialog):
        Dialog.setObjectName("Dialog")
        Dialog.resize(381, 622)
        Dialog.setStyleSheet("background: #919191;")
        self.textEdit = QtWidgets.QTextEdit(Dialog)
        self.textEdit.setGeometry(QtCore.QRect(30, 70, 311, 81))
        self.textEdit.setStyleSheet("background: #DFDFDF;\n"
"\n"
"vertical-align: text-bottom;\n"
"font: 48pt \"MS Shell Dlg 2\";")
        self.textEdit.setObjectName("textEdit")
        self.pushButton_power = QtWidgets.QPushButton(Dialog)
        self.pushButton_power.setGeometry(QtCore.QRect(30, 160, 71, 71))
        self.pushButton_power.setStyleSheet("background: #545454;\n"
"color: #fff;\n"
"font-size: 22px;\n"
"border-radius: 14px;\n"
"hover {\n"
"    background: #474747;\n"
"}")
        self.pushButton_power.setObjectName("pushButton_power")
        self.pushButton_root = QtWidgets.QPushButton(Dialog)
        self.pushButton_root.setGeometry(QtCore.QRect(110, 160, 71, 71))
        self.pushButton_root.setStyleSheet("background: #545454;\n"
"color: #fff;\n"
"font-size: 22px;\n"
"border-radius: 14px;\n"
"hover {\n"
"    background: #474747;\n"
"}")
        self.pushButton_root.setObjectName("pushButton_root")
        self.pushButton_multi = QtWidgets.QPushButton(Dialog)
        self.pushButton_multi.setGeometry(QtCore.QRect(190, 160, 71, 71))
        self.pushButton_multi.setStyleSheet("background: #545454;\n"
"color: #fff;\n"
"font-size: 22px;\n"
"border-radius: 14px;\n"
"hover {\n"
"    background: #474747;\n"
"}")
        self.pushButton_multi.setObjectName("pushButton_multi")
        self.pushButton_division = QtWidgets.QPushButton(Dialog)
        self.pushButton_division.setGeometry(QtCore.QRect(270, 160, 71, 71))
        self.pushButton_division.setStyleSheet("background: #545454;\n"
"color: #fff;\n"
"font-size: 22px;\n"
"border-radius: 14px;\n"
"hover {\n"
"    background: #474747;\n"
"}")
        self.pushButton_division.setObjectName("pushButton_division")
        self.pushButton_minus = QtWidgets.QPushButton(Dialog)
        self.pushButton_minus.setGeometry(QtCore.QRect(270, 240, 71, 71))
        self.pushButton_minus.setStyleSheet("background: #545454;\n"
"color: #fff;\n"
"font-size: 22px;\n"
"border-radius: 14px;\n"
"hover {\n"
"    background: #474747;\n"
"}")
        self.pushButton_minus.setObjectName("pushButton_minus")
        self.pushButton_8 = QtWidgets.QPushButton(Dialog)
        self.pushButton_8.setGeometry(QtCore.QRect(110, 240, 71, 71))
        self.pushButton_8.setStyleSheet("background: #545454;\n"
"color: #fff;\n"
"font-size: 22px;\n"
"border-radius: 14px;\n"
"hover {\n"
"    background: #474747;\n"
"}")
        self.pushButton_8.setObjectName("pushButton_8")
        self.pushButton_7 = QtWidgets.QPushButton(Dialog)
        self.pushButton_7.setGeometry(QtCore.QRect(30, 240, 71, 71))
        self.pushButton_7.setStyleSheet("background: #545454;\n"
"color: #fff;\n"
"font-size: 22px;\n"
"border-radius: 14px;\n"
"hover {\n"
"    background: #474747;\n"
"}")
        self.pushButton_7.setObjectName("pushButton_7")
        self.pushButton_9 = QtWidgets.QPushButton(Dialog)
        self.pushButton_9.setGeometry(QtCore.QRect(190, 240, 71, 71))
        self.pushButton_9.setStyleSheet("background: #545454;\n"
"color: #fff;\n"
"font-size: 22px;\n"
"border-radius: 14px;\n"
"hover {\n"
"    background: #474747;\n"
"}")
        self.pushButton_9.setObjectName("pushButton_9")
        self.pushButton_2 = QtWidgets.QPushButton(Dialog)
        self.pushButton_2.setGeometry(QtCore.QRect(110, 400, 71, 71))
        self.pushButton_2.setStyleSheet("background: #545454;\n"
"color: #fff;\n"
"font-size: 22px;\n"
"border-radius: 14px;\n"
"hover {\n"
"    background: #474747;\n"
"}")
        self.pushButton_2.setObjectName("pushButton_2")
        self.pushButton_plus = QtWidgets.QPushButton(Dialog)
        self.pushButton_plus.setGeometry(QtCore.QRect(270, 320, 71, 71))
        self.pushButton_plus.setStyleSheet("background: #545454;\n"
"color: #fff;\n"
"font-size: 22px;\n"
"border-radius: 14px;\n"
"hover {\n"
"    background: #474747;\n"
"}")
        self.pushButton_plus.setObjectName("pushButton_plus")
        self.pushButton_1 = QtWidgets.QPushButton(Dialog)
        self.pushButton_1.setGeometry(QtCore.QRect(30, 400, 71, 71))
        self.pushButton_1.setStyleSheet("background: #545454;\n"
"color: #fff;\n"
"font-size: 22px;\n"
"border-radius: 14px;\n"
"hover {\n"
"    background: #474747;\n"
"}")
        self.pushButton_1.setObjectName("pushButton_1")
        self.pushButton_5 = QtWidgets.QPushButton(Dialog)
        self.pushButton_5.setGeometry(QtCore.QRect(110, 320, 71, 71))
        self.pushButton_5.setStyleSheet("background: #545454;\n"
"color: #fff;\n"
"font-size: 22px;\n"
"border-radius: 14px;\n"
"hover {\n"
"    background: #474747;\n"
"}")
        self.pushButton_5.setObjectName("pushButton_5")
        self.pushButton_4 = QtWidgets.QPushButton(Dialog)
        self.pushButton_4.setGeometry(QtCore.QRect(30, 320, 71, 71))
        self.pushButton_4.setStyleSheet("background: #545454;\n"
"color: #fff;\n"
"font-size: 22px;\n"
"border-radius: 14px;\n"
"hover {\n"
"    background: #474747;\n"
"}")
        self.pushButton_4.setObjectName("pushButton_4")
        self.pushButton_6 = QtWidgets.QPushButton(Dialog)
        self.pushButton_6.setGeometry(QtCore.QRect(190, 320, 71, 71))
        self.pushButton_6.setStyleSheet("background: #545454;\n"
"color: #fff;\n"
"font-size: 22px;\n"
"border-radius: 14px;\n"
"hover {\n"
"    background: #474747;\n"
"}")
        self.pushButton_6.setObjectName("pushButton_6")
        self.pushButton_equal = QtWidgets.QPushButton(Dialog)
        self.pushButton_equal.setGeometry(QtCore.QRect(270, 400, 71, 151))
        self.pushButton_equal.setStyleSheet("background: #bd2d02;\n"
"color: #fff;\n"
"font-size: 22px;\n"
"border-radius: 14px;\n"
"hover {\n"
"    background: #9e2500;\n"
"}")
        self.pushButton_equal.setObjectName("pushButton_equal")
        self.pushButton_3 = QtWidgets.QPushButton(Dialog)
        self.pushButton_3.setGeometry(QtCore.QRect(190, 400, 71, 71))
        self.pushButton_3.setStyleSheet("background: #545454;\n"
"color: #fff;\n"
"font-size: 22px;\n"
"border-radius: 14px;\n"
"hover {\n"
"    background: #474747;\n"
"}")
        self.pushButton_3.setObjectName("pushButton_3")
        self.pushButton_clear = QtWidgets.QPushButton(Dialog)
        self.pushButton_clear.setGeometry(QtCore.QRect(30, 480, 71, 71))
        self.pushButton_clear.setStyleSheet("background: #545454;\n"
"color: #fff;\n"
"font-size: 22px;\n"
"border-radius: 14px;\n"
"hover {\n"
"    background: #474747;\n"
"}")
        self.pushButton_clear.setObjectName("pushButton_clear")
        self.pushButton_0 = QtWidgets.QPushButton(Dialog)
        self.pushButton_0.setGeometry(QtCore.QRect(110, 480, 71, 71))
        self.pushButton_0.setStyleSheet("background: #545454;\n"
"color: #fff;\n"
"font-size: 22px;\n"
"border-radius: 14px;\n"
"hover {\n"
"    background: #474747;\n"
"}")
        self.pushButton_0.setObjectName("pushButton_0")
        self.pushButton_clearAll = QtWidgets.QPushButton(Dialog)
        self.pushButton_clearAll.setGeometry(QtCore.QRect(190, 480, 71, 71))
        self.pushButton_clearAll.setStyleSheet("background: #545454;\n"
"color: #fff;\n"
"font-size: 22px;\n"
"border-radius: 14px;\n"
"hover {\n"
"    background: #474747;\n"
"}")
        self.pushButton_clearAll.setObjectName("pushButton_clearAll")

        self.retranslateUi(Dialog)
        QtCore.QMetaObject.connectSlotsByName(Dialog)

    def retranslateUi(self, Dialog):
        _translate = QtCore.QCoreApplication.translate
        Dialog.setWindowTitle(_translate("Dialog", "Dialog"))
        self.textEdit.setHtml(_translate("Dialog", "<!DOCTYPE HTML PUBLIC \"-//W3C//DTD HTML 4.0//EN\" \"http://www.w3.org/TR/REC-html40/strict.dtd\">\n"
"<html><head><meta name=\"qrichtext\" content=\"1\" /><style type=\"text/css\">\n"
"p, li { white-space: pre-wrap; }\n"
"</style></head><body style=\" font-family:\'MS Shell Dlg 2\'; font-size:40pt; font-weight:400; font-style:normal;\">\n"
"<p align=\"right\" style=\" margin-top:0px; margin-bottom:0px; margin-left:0px; margin-right:0px; -qt-block-indent:0; text-indent:0px;\"><span style=\" font-size:36pt;\"></span></p></body></html>"))
        self.pushButton_power.setText(_translate("Dialog", "**"))
        self.pushButton_root.setText(_translate("Dialog", "√"))
        self.pushButton_multi.setText(_translate("Dialog", "*"))
        self.pushButton_division.setText(_translate("Dialog", "/"))
        self.pushButton_minus.setText(_translate("Dialog", "-"))
        self.pushButton_8.setText(_translate("Dialog", "8"))
        self.pushButton_7.setText(_translate("Dialog", "7"))
        self.pushButton_9.setText(_translate("Dialog", "9"))
        self.pushButton_2.setText(_translate("Dialog", "2"))
        self.pushButton_plus.setText(_translate("Dialog", "+"))
        self.pushButton_1.setText(_translate("Dialog", "1"))
        self.pushButton_5.setText(_translate("Dialog", "5"))
        self.pushButton_4.setText(_translate("Dialog", "4"))
        self.pushButton_6.setText(_translate("Dialog", "6"))
        self.pushButton_equal.setText(_translate("Dialog", "="))
        self.pushButton_3.setText(_translate("Dialog", "3"))
        self.pushButton_clear.setText(_translate("Dialog", "C"))
        self.pushButton_0.setText(_translate("Dialog", "0"))
        self.pushButton_clearAll.setText(_translate("Dialog", "CE"))
